# Generated by Django 3.0.1 on 2019-12-24 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category_date', models.DateTimeField(default=datetime.datetime.now)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moderators.Moderator')),
            ],
        ),
    ]
